jobs:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
    - os: linux
      dist: precise

services:
  - docker

script:
  - sandbox up
